# Generated by Django 3.1 on 2022-07-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maker_website', models.URLField(max_length=100)),
                ('z', models.PositiveIntegerField()),
            ],
        ),
    ]
